language: scala
git:
  depth: 300
matrix:
  include:
    - os: linux
      jdk: openjdk11
      scala: 2.12.11
    - os: linux
      jdk: openjdk8
      scala: 2.11.12
cache: sbt
script:
  - travis_wait 60 sbt -batch ++$TRAVIS_SCALA_VERSION! clean coverage test coverageReport mimaReportBinaryIssues < /dev/null
after_success:
  - bash <(curl -s https://codecov.io/bash)
