language: scala
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      scala: 2.12.8
    - os: linux
      jdk: openjdk8
      scala: 2.11.12
cache: sbt
script:
  - travis_wait sbt -no-colors ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport mimaReportBinaryIssues
after_success:
  - bash <(curl -s https://codecov.io/bash)
