language: scala
matrix:
  include:
    - os: osx
      osx_image: xcode10.1 # macOS 10.13, JDK 11.0.1+13
      scala: 2.12.8
    - os: linux
      jdk: openjdk8
      scala: 2.12.8
cache: sbt
script:
  - travis_wait sbt -no-colors ++$TRAVIS_SCALA_VERSION -Dsbt.supershell=false clean coverage test coverageReport mimaReportBinaryIssues
after_success:
  - bash <(curl -s https://codecov.io/bash)
